key: area_infrastructure
groups:
  - header: area_electricity_grid_costs
    items:
      - key: lv_net_total_costs_present
        unit: '€'
      - key: mv_net_total_costs_present
        unit: '€'
      - key: hv_net_total_costs_present
        unit: '€'
      - key: lv_mv_trafo_total_costs_present
        unit: '€'
      - key: mv_hv_trafo_total_costs_present
        unit: '€'
      - key: offshore_net_costs_present
        unit: '€'
      - key: interconnection_net_costs_present
        unit: '€'

  - header: area_gas_grid_costs
    items:
      - key: annual_infrastructure_cost_gas
        unit: '€'

  - header: area_electricity_grid_capacity
    type: slider
    combination_method: average
    items:
      - key: lv_net_spare_capacity
        unit: '%'
      - key: mv_net_spare_capacity
        unit: '%'
      - key: hv_net_spare_capacity
        unit: '%'
      - key: lv_mv_trafo_spare_capacity
        unit: '%'
      - key: mv_hv_trafo_spare_capacity
        unit: '%'

  - header: area_interconnector_capacity
    items:
      - key: interconnector_capacity
        unit: 'MW'

  - header: area_electricity_grid_reinforcement
    combination_method: min
    items:
      - key: lv_net_capacity_per_step
        unit: 'MW'
      - key: lv_net_costs_per_capacity_step
        unit: '€'
      - key: mv_net_capacity_per_step
        unit: 'MW'
      - key: mv_net_costs_per_capacity_step
        unit: '€'
      - key: hv_net_capacity_per_step
        unit: 'MW'
      - key: hv_net_costs_per_capacity_step
        unit: '€'
      - key: lv_mv_trafo_capacity_per_step
        unit: 'MW'
      - key: lv_mv_trafo_costs_per_capacity_step
        unit: '€'
      - key: mv_hv_trafo_capacity_per_step
        unit: 'MW'
      - key: mv_hv_trafo_costs_per_capacity_step
        unit: '€'

  - header: area_heat_infrastructure_lengths
    items:
      - key: heat_length_of_distribution_pipelines_in_meter_per_residence_object_first_bracket
        unit: 'meter'
        combination_method:
          weighted_average:
            - sum:
              - present_number_of_apartments_before_1945
              - present_number_of_apartments_1945_1964
              - present_number_of_apartments_1965_1984
              - present_number_of_apartments_1985_2004
              - present_number_of_apartments_2005_present
              - present_number_of_detached_houses_before_1945
              - present_number_of_detached_houses_1945_1964
              - present_number_of_detached_houses_1965_1984
              - present_number_of_detached_houses_1985_2004
              - present_number_of_detached_houses_2005_present
              - present_number_of_semi_detached_houses_before_1945
              - present_number_of_semi_detached_houses_1945_1964
              - present_number_of_semi_detached_houses_1965_1984
              - present_number_of_semi_detached_houses_1985_2004
              - present_number_of_semi_detached_houses_2005_present
              - present_number_of_terraced_houses_before_1945
              - present_number_of_terraced_houses_1945_1964
              - present_number_of_terraced_houses_1965_1984
              - present_number_of_terraced_houses_1985_2004
              - present_number_of_terraced_houses_2005_present
      - key: heat_length_of_distribution_pipelines_in_meter_per_residence_object_second_bracket
        unit: 'meter'
        combination_method:
          weighted_average:
            - sum:
              - present_number_of_apartments_before_1945
              - present_number_of_apartments_1945_1964
              - present_number_of_apartments_1965_1984
              - present_number_of_apartments_1985_2004
              - present_number_of_apartments_2005_present
              - present_number_of_detached_houses_before_1945
              - present_number_of_detached_houses_1945_1964
              - present_number_of_detached_houses_1965_1984
              - present_number_of_detached_houses_1985_2004
              - present_number_of_detached_houses_2005_present
              - present_number_of_semi_detached_houses_before_1945
              - present_number_of_semi_detached_houses_1945_1964
              - present_number_of_semi_detached_houses_1965_1984
              - present_number_of_semi_detached_houses_1985_2004
              - present_number_of_semi_detached_houses_2005_present
              - present_number_of_terraced_houses_before_1945
              - present_number_of_terraced_houses_1945_1964
              - present_number_of_terraced_houses_1965_1984
              - present_number_of_terraced_houses_1985_2004
              - present_number_of_terraced_houses_2005_present
      - key: heat_length_of_distribution_pipelines_in_meter_per_residence_object_third_bracket
        unit: 'meter'
        combination_method:
          weighted_average:
            - sum:
              - present_number_of_apartments_before_1945
              - present_number_of_apartments_1945_1964
              - present_number_of_apartments_1965_1984
              - present_number_of_apartments_1985_2004
              - present_number_of_apartments_2005_present
              - present_number_of_detached_houses_before_1945
              - present_number_of_detached_houses_1945_1964
              - present_number_of_detached_houses_1965_1984
              - present_number_of_detached_houses_1985_2004
              - present_number_of_detached_houses_2005_present
              - present_number_of_semi_detached_houses_before_1945
              - present_number_of_semi_detached_houses_1945_1964
              - present_number_of_semi_detached_houses_1965_1984
              - present_number_of_semi_detached_houses_1985_2004
              - present_number_of_semi_detached_houses_2005_present
              - present_number_of_terraced_houses_before_1945
              - present_number_of_terraced_houses_1945_1964
              - present_number_of_terraced_houses_1965_1984
              - present_number_of_terraced_houses_1985_2004
              - present_number_of_terraced_houses_2005_present
      - key: heat_length_of_distribution_pipelines_in_meter_per_residence_object_fourth_bracket
        unit: 'meter'
        combination_method:
          weighted_average:
            - sum:
              - present_number_of_apartments_before_1945
              - present_number_of_apartments_1945_1964
              - present_number_of_apartments_1965_1984
              - present_number_of_apartments_1985_2004
              - present_number_of_apartments_2005_present
              - present_number_of_detached_houses_before_1945
              - present_number_of_detached_houses_1945_1964
              - present_number_of_detached_houses_1965_1984
              - present_number_of_detached_houses_1985_2004
              - present_number_of_detached_houses_2005_present
              - present_number_of_semi_detached_houses_before_1945
              - present_number_of_semi_detached_houses_1945_1964
              - present_number_of_semi_detached_houses_1965_1984
              - present_number_of_semi_detached_houses_1985_2004
              - present_number_of_semi_detached_houses_2005_present
              - present_number_of_terraced_houses_before_1945
              - present_number_of_terraced_houses_1945_1964
              - present_number_of_terraced_houses_1965_1984
              - present_number_of_terraced_houses_1985_2004
              - present_number_of_terraced_houses_2005_present
      - key: heat_length_of_distribution_pipelines_in_meter_per_residence_object_fifth_bracket
        unit: 'meter'
        combination_method:
          weighted_average:
            - sum:
              - present_number_of_apartments_before_1945
              - present_number_of_apartments_1945_1964
              - present_number_of_apartments_1965_1984
              - present_number_of_apartments_1985_2004
              - present_number_of_apartments_2005_present
              - present_number_of_detached_houses_before_1945
              - present_number_of_detached_houses_1945_1964
              - present_number_of_detached_houses_1965_1984
              - present_number_of_detached_houses_1985_2004
              - present_number_of_detached_houses_2005_present
              - present_number_of_semi_detached_houses_before_1945
              - present_number_of_semi_detached_houses_1945_1964
              - present_number_of_semi_detached_houses_1965_1984
              - present_number_of_semi_detached_houses_1985_2004
              - present_number_of_semi_detached_houses_2005_present
              - present_number_of_terraced_houses_before_1945
              - present_number_of_terraced_houses_1945_1964
              - present_number_of_terraced_houses_1965_1984
              - present_number_of_terraced_houses_1985_2004
              - present_number_of_terraced_houses_2005_present
      - key: heat_length_of_connection_pipelines_in_meter_per_residence_first_bracket
        unit: 'meter'
        combination_method:
          weighted_average:
            - sum:
              - present_number_of_apartments_before_1945
              - present_number_of_apartments_1945_1964
              - present_number_of_apartments_1965_1984
              - present_number_of_apartments_1985_2004
              - present_number_of_apartments_2005_present
              - present_number_of_detached_houses_before_1945
              - present_number_of_detached_houses_1945_1964
              - present_number_of_detached_houses_1965_1984
              - present_number_of_detached_houses_1985_2004
              - present_number_of_detached_houses_2005_present
              - present_number_of_semi_detached_houses_before_1945
              - present_number_of_semi_detached_houses_1945_1964
              - present_number_of_semi_detached_houses_1965_1984
              - present_number_of_semi_detached_houses_1985_2004
              - present_number_of_semi_detached_houses_2005_present
              - present_number_of_terraced_houses_before_1945
              - present_number_of_terraced_houses_1945_1964
              - present_number_of_terraced_houses_1965_1984
              - present_number_of_terraced_houses_1985_2004
              - present_number_of_terraced_houses_2005_present
      - key: heat_length_of_connection_pipelines_in_meter_per_residence_second_bracket
        unit: 'meter'
        combination_method:
          weighted_average:
            - sum:
              - present_number_of_apartments_before_1945
              - present_number_of_apartments_1945_1964
              - present_number_of_apartments_1965_1984
              - present_number_of_apartments_1985_2004
              - present_number_of_apartments_2005_present
              - present_number_of_detached_houses_before_1945
              - present_number_of_detached_houses_1945_1964
              - present_number_of_detached_houses_1965_1984
              - present_number_of_detached_houses_1985_2004
              - present_number_of_detached_houses_2005_present
              - present_number_of_semi_detached_houses_before_1945
              - present_number_of_semi_detached_houses_1945_1964
              - present_number_of_semi_detached_houses_1965_1984
              - present_number_of_semi_detached_houses_1985_2004
              - present_number_of_semi_detached_houses_2005_present
              - present_number_of_terraced_houses_before_1945
              - present_number_of_terraced_houses_1945_1964
              - present_number_of_terraced_houses_1965_1984
              - present_number_of_terraced_houses_1985_2004
              - present_number_of_terraced_houses_2005_present
      - key: heat_length_of_connection_pipelines_in_meter_per_residence_third_bracket
        unit: 'meter'
        combination_method:
          weighted_average:
            - sum:
              - present_number_of_apartments_before_1945
              - present_number_of_apartments_1945_1964
              - present_number_of_apartments_1965_1984
              - present_number_of_apartments_1985_2004
              - present_number_of_apartments_2005_present
              - present_number_of_detached_houses_before_1945
              - present_number_of_detached_houses_1945_1964
              - present_number_of_detached_houses_1965_1984
              - present_number_of_detached_houses_1985_2004
              - present_number_of_detached_houses_2005_present
              - present_number_of_semi_detached_houses_before_1945
              - present_number_of_semi_detached_houses_1945_1964
              - present_number_of_semi_detached_houses_1965_1984
              - present_number_of_semi_detached_houses_1985_2004
              - present_number_of_semi_detached_houses_2005_present
              - present_number_of_terraced_houses_before_1945
              - present_number_of_terraced_houses_1945_1964
              - present_number_of_terraced_houses_1965_1984
              - present_number_of_terraced_houses_1985_2004
              - present_number_of_terraced_houses_2005_present
      - key: heat_length_of_connection_pipelines_in_meter_per_residence_fourth_bracket
        unit: 'meter'
        combination_method:
          weighted_average:
            - sum:
              - present_number_of_apartments_before_1945
              - present_number_of_apartments_1945_1964
              - present_number_of_apartments_1965_1984
              - present_number_of_apartments_1985_2004
              - present_number_of_apartments_2005_present
              - present_number_of_detached_houses_before_1945
              - present_number_of_detached_houses_1945_1964
              - present_number_of_detached_houses_1965_1984
              - present_number_of_detached_houses_1985_2004
              - present_number_of_detached_houses_2005_present
              - present_number_of_semi_detached_houses_before_1945
              - present_number_of_semi_detached_houses_1945_1964
              - present_number_of_semi_detached_houses_1965_1984
              - present_number_of_semi_detached_houses_1985_2004
              - present_number_of_semi_detached_houses_2005_present
              - present_number_of_terraced_houses_before_1945
              - present_number_of_terraced_houses_1945_1964
              - present_number_of_terraced_houses_1965_1984
              - present_number_of_terraced_houses_1985_2004
              - present_number_of_terraced_houses_2005_present
      - key: heat_length_of_connection_pipelines_in_meter_per_residence_fifth_bracket
        unit: 'meter'
        combination_method:
          weighted_average:
            - sum:
              - present_number_of_apartments_before_1945
              - present_number_of_apartments_1945_1964
              - present_number_of_apartments_1965_1984
              - present_number_of_apartments_1985_2004
              - present_number_of_apartments_2005_present
              - present_number_of_detached_houses_before_1945
              - present_number_of_detached_houses_1945_1964
              - present_number_of_detached_houses_1965_1984
              - present_number_of_detached_houses_1985_2004
              - present_number_of_detached_houses_2005_present
              - present_number_of_semi_detached_houses_before_1945
              - present_number_of_semi_detached_houses_1945_1964
              - present_number_of_semi_detached_houses_1965_1984
              - present_number_of_semi_detached_houses_1985_2004
              - present_number_of_semi_detached_houses_2005_present
              - present_number_of_terraced_houses_before_1945
              - present_number_of_terraced_houses_1945_1964
              - present_number_of_terraced_houses_1965_1984
              - present_number_of_terraced_houses_1985_2004
              - present_number_of_terraced_houses_2005_present
