key: area
groups:
  - header:
    combination_method: sum
    items:
      - key: has_merit_order
        unit: 'string'
      - key: has_mountains
        unit: 'string'
      - key: has_offshore_solar
        unit: 'string'
      - key: has_solar_csp
        unit: 'string'
      - key: has_weather_curves
        unit: 'string'
