key: area
groups:
  - header: area_details
    combination_method: max
    items:
      - key: analysis_year
        unit: '#'
      - key: parent
        unit: 'string'
        skip_validation: true
      - key: has_merit_order
        unit: 'boolean'
