key: area_geography
groups:
  - header:
    items:
    - key: total_land_area
      unit: 'km<sup>2</sup>'
    - key: areable_land
      unit: 'km<sup>2</sup>'
    - key: offshore_suitable_for_wind
      unit: 'km<sup>2</sup>'
      combination_method: average
    - key: coast_line
      unit: 'km'
    - key: has_mountains
      unit: 'boolean'
      combination_method: max
    - key: has_offshore_solar
      unit: 'boolean'
      combination_method: max
    - key: has_solar_csp
      unit: 'boolean'
      combination_method: max
    - key: has_weather_curves
      unit: 'boolean'
      combination_method: max
