key: area
groups:
  - header:
    combination_method: min
    items:
      - key: analysis_year
        unit: '#'
      - key: parent
        unit: 'string'
        skip_validation: true
  - header: area_details
    combination_method: max
    items:
      - key: has_mountains
        unit: 'boolean'
      - key: has_offshore_solar
        unit: 'boolean'
      - key: has_solar_csp
        unit: 'boolean'
      - key: has_merit_order
        unit: 'boolean'
      - key: has_weather_curves
        unit: 'boolean'
