version: '3'

services:
  web: &web
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - ../etsource:/etsource:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
      - storage:/app/storage
    environment:
      - DATABASE_HOST=database
      - MAPBOX_API_KEY
      - MYSQL_DATABASE=etlocal_development
      - MYSQL_PASSWORD=dev
      - MYSQL_USER=root
    tmpfs:
      - /tmp
    depends_on:
      - database

  database:
    # Using MariaDB instead of MySQL since it offers support for arm64
    image: mariadb:latest
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=etlocal_development
    volumes:
      - db_data:/var/lib/mysql

volumes:
  bundle:
  db_data:
  node_modules:
  packs:
  rails_cache:
  storage:
