key: supply_fossil_production
groups:
  - header: electricity
    items:
      energy_power_ultra_supercritical_coal_demand:
      energy_power_ultra_supercritical_cofiring_coal_demand:
      energy_power_ultra_supercritical_ccs_coal_demand:
      energy_power_combined_cycle_coal_demand:
      energy_power_combined_cycle_ccs_coal_demand:
      energy_power_supercritical_coal_demand:
      energy_power_combined_cycle_network_gas_demand:
      energy_power_combined_cycle_ccs_network_gas_demand:
      energy_power_turbine_network_gas_demand:
      energy_power_engine_network_gas_demand:
      energy_power_ultra_supercritical_network_gas_demand:
      energy_power_nuclear_gen2_uranium_oxide_demand:
      energy_power_nuclear_gen3_uranium_oxide_demand:
      energy_power_ultra_supercritical_crude_oil_demand:
      energy_power_engine_diesel_demand:

  - header: central_production_heat_networks
    items:
      energy_heater_for_heat_network_network_gas_demand:
      energy_chp_combined_cycle_network_gas_demand:
      energy_heater_for_heat_network_coal_demand:
      energy_chp_ultra_supercritical_coal_demand:
      energy_chp_ultra_supercritical_cofiring_coal_demand:
      energy_heater_for_heat_network_crude_oil_demand:
