key: industry

groups:
  - header: industry_chps
    items:
      - key: industry_chp_combined_cycle_gas_power_fuelmix_demand
        unit: 'TJ'
      - key: industry_chp_engine_gas_power_fuelmix_demand
        unit: 'TJ'
      - key: industry_chp_turbine_gas_power_fuelmix_demand
        unit: 'TJ'
      - key: industry_chp_ultra_supercritical_coal_demand
        unit: 'TJ'