key: industry

groups:
  - header: industry_final_demand_crude_oil_input
    type: slider
    combination_method:
      weighted_average:
        - sum:
          - input_industry_chemical_other_crude_oil_demand
          - input_industry_chemical_fertilizers_crude_oil_demand
          - input_industry_food_crude_oil_demand
          - input_industry_metal_other_crude_oil_demand
          - input_industry_other_crude_oil_demand
          - input_industry_paper_crude_oil_demand
          - input_industry_chemical_refineries_crude_oil_demand
          - input_industry_metal_steel_crude_oil_demand
    items:
    - key: input_percentage_of_diesel_industry_final_demand_crude_oil
      unit: '%'
      entso: |
        EB("Final consumption - industry sector - energy use", "Gas oil and diesel oil (excluding biofuel portion)") /
        EB("Final consumption - industry sector - energy use", "Oil excluding naphtha")
    - key: input_percentage_of_biodiesel_industry_final_demand_crude_oil
      unit: '%'
      entso: |
        EB("Final consumption - industry sector - energy use", "Bio-diesel") /
        EB("Final consumption - industry sector - energy use", "Oil excluding naphtha")
    - key: input_percentage_of_kerosene_industry_final_demand_crude_oil
      unit: '%'
      entso: |
        EB("Final consumption - industry sector - energy use", "Kerosene") /
        EB("Final consumption - industry sector - energy use", "Oil excluding naphtha")
    - key: input_percentage_of_bio_kerosene_industry_final_demand_crude_oil
      unit: '%'
      entso: |
        EB("Final consumption - industry sector - energy use", "Bio-kerosene") /
        EB("Final consumption - industry sector - energy use", "Oil excluding naphtha")
    - key: input_percentage_of_lpg_industry_final_demand_crude_oil
      unit: '%'
      entso: |
        EB("Final consumption - industry sector - energy use", "Liquefied petroleum gases") /
        EB("Final consumption - industry sector - energy use", "Oil excluding naphtha")
    - key: input_percentage_of_bio_oil_industry_final_demand_crude_oil
      unit: '%'
      entso: |
        (EB("Final consumption - industry sector - energy use", "Biogasoline") +
        EB("Final consumption - industry sector - energy use", "Other liquid biofuels")) /
        EB("Final consumption - industry sector - energy use", "Oil excluding naphtha")
    - key: input_percentage_of_crude_oil_industry_final_demand_crude_oil
      unit: '%'
      entso: |
        EB("Final consumption - industry sector - energy use", "Other oil") /
        EB("Final consumption - industry sector - energy use", "Oil excluding naphtha")
      flexible: true
      skip_validation: true

  - header: industry_final_demand_crude_oil_non_energetic_input
    type: slider
    combination_method:
      weighted_average:
        - sum:
          - input_industry_chemical_other_crude_oil_non_energetic_demand
          - input_industry_chemical_fertilizers_crude_oil_non_energetic_demand
          - input_industry_other_crude_oil_non_energetic_demand
    items:
    - key: input_percentage_of_diesel_industry_final_demand_crude_oil_non_energetic
      unit: '%'
      entso: |
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Gas oil and diesel oil (excluding biofuel portion)") /
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Oil excluding naphtha")
    - key: input_percentage_of_biodiesel_industry_final_demand_crude_oil_non_energetic
      unit: '%'
      entso: |
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Bio-diesel") /
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Oil excluding naphtha")
    - key: input_percentage_of_kerosene_industry_final_demand_crude_oil_non_energetic
      unit: '%'
      entso: |
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Kerosene") /
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Oil excluding naphtha")
    - key: input_percentage_of_bio_kerosene_industry_final_demand_crude_oil_non_energetic
      unit: '%'
      entso: |
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Bio-kerosene") /
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Oil excluding naphtha")
    - key: input_percentage_of_lpg_industry_final_demand_crude_oil_non_energetic
      unit: '%'
      entso: |
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Liquefied petroleum gases") /
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Oil excluding naphtha")
    - key: input_percentage_of_bio_oil_industry_final_demand_crude_oil_non_energetic
      unit: '%'
      entso: |
        (EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Biogasoline") +
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Other liquid biofuels")) /
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Oil excluding naphtha")
    - key: input_percentage_of_crude_oil_industry_final_demand_crude_oil_non_energetic
      unit: '%'
      entso: |
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Other oil") /
        EB("Transformation input, energy sector and final consumption in industry sector - non-energy use", "Oil excluding naphtha")
      flexible: true
      skip_validation: true
