key: industry_metal_old

groups:
  - header: industry_metal_other_old
    items:
      - key: input_industry_metal_other_electricity_demand
        unit: 'TJ'
      - key: input_industry_metal_other_network_gas_demand
        unit: 'TJ'
      - key: input_industry_metal_other_steam_hot_water_demand
        unit: 'TJ'
      - key: input_industry_metal_other_crude_oil_demand
        unit: 'TJ'
      - key: input_industry_metal_other_coal_demand
        unit: 'TJ'
