key: industry
groups:
  - header: industry_heat
    items:
      - key: industry_chp_combined_cycle_gas_power_fuelmix_demand
        unit: 'TJ'
      - key: industry_chp_engine_gas_power_fuelmix_demand
        unit: 'TJ'
      - key: industry_chp_turbine_gas_power_fuelmix_demand
        unit: 'TJ'
      - key: industry_chp_ultra_supercritical_coal_demand
        unit: 'TJ'
      - key: industry_chp_wood_pellets_demand
        unit: 'TJ'
      - key: industry_heat_burner_lignite_demand
        unit: 'TJ'
      - key: industry_heat_burner_coal_demand
        unit: 'TJ'
      - key: industry_heat_well_geothermal_demand
        unit: 'TJ'
      - key: industry_heat_burner_crude_oil
        unit: 'TJ'

  - header: industry_gas_fuelmix
    type: slider
    items:
      - key: input_share_mixer_gas_fuel_bio_oil
        unit: '%'
      - key: input_share_mixer_gas_fuel_oil
        unit: '%'
      - key: input_share_mixer_gas_fuel_network_gas
        unit: '%'
        flexible: true
