key: households_housing_stock
groups:
  - header:
    items:
      - key: number_of_inhabitants
        unit: '#'
      - key: residences_roof_surface_available_for_pv
        unit: 'km<sup>2</sup>'

  - header: households_housing_stock_apartments
    type: slider
    items:
      - key: households_number_of_apartments_2005
        unit: '#'
      - key: households_number_of_apartments_1985_2004
        unit: '#'
      - key: households_number_of_apartments_1965_1984
        unit: '#'
      - key: households_number_of_apartments_1945_1964
        unit: '#'
      - key: households_number_of_apartments_1945
        unit: '#'
  
  - header: households_housing_stock_terraced
    type: slider
    items:
      - key: households_number_of_terraced_2005
        unit: '#'
      - key: households_number_of_terraced_1985_2004
        unit: '#'
      - key: households_number_of_terraced_1965_1984
        unit: '#'
      - key: households_number_of_terraced_1945_1964
        unit: '#'
      - key: households_number_of_terraced_1945
        unit: '#'

  - header: households_housing_stock_semi_detached
    type: slider
    items:
      - key: households_number_of_semi_detached_2005
        unit: '#'
      - key: households_number_of_semi_detached_1985_2004
        unit: '#'
      - key: households_number_of_semi_detached_1965_1984
        unit: '#'
      - key: households_number_of_semi_detached_1945_1964
        unit: '#'
      - key: households_number_of_semi_detached_1945
        unit: '#'

  - header: households_housing_stock_detached
    type: slider
    items:
      - key: households_number_of_detached_2005
        unit: '#'
      - key: households_number_of_detached_1985_2004
        unit: '#'
      - key: households_number_of_detached_1965_1984
        unit: '#'
      - key: households_number_of_detached_1945_1964
        unit: '#'
      - key: households_number_of_detached_1945
        unit: '#'