key: households_housing_stock
groups:
  - header:
    items:
      - key: number_of_inhabitants
        unit: '#'
      - key: residences_roof_surface_available_for_pv
        unit: 'km<sup>2</sup>'

  - header: households_housing_stock_apartments
    type: slider
    items:
      - key: present_number_of_apartments_before_1945
        unit: '#'
      - key: present_number_of_apartments_1945_1964
        unit: '#'
      - key: present_number_of_apartments_1965_1984
        unit: '#'
      - key: present_number_of_apartments_1985_2004
        unit: '#'
      - key: present_number_of_apartments_2005_present
        unit: '#'

  - header: households_housing_stock_detached_houses
    type: slider
    items:
      - key: present_number_of_detached_houses_before_1945
        unit: '#'
      - key: present_number_of_detached_houses_1945_1964
        unit: '#'
      - key: present_number_of_detached_houses_1965_1984
        unit: '#'
      - key: present_number_of_detached_houses_1985_2004
        unit: '#'
      - key: present_number_of_detached_houses_2005_present
        unit: '#'

  - header: households_housing_stock_semi_detached_houses
    type: slider
    items:
      - key: present_number_of_semi_detached_houses_before_1945
        unit: '#'
      - key: present_number_of_semi_detached_houses_1945_1964
        unit: '#'
      - key: present_number_of_semi_detached_houses_1965_1984
        unit: '#'
      - key: present_number_of_semi_detached_houses_1985_2004
        unit: '#'
      - key: present_number_of_semi_detached_houses_2005_present
        unit: '#'

  - header: households_housing_stock_terraced_houses
    type: slider
    items:
      - key: present_number_of_terraced_houses_before_1945
        unit: '#'
      - key: present_number_of_terraced_houses_1945_1964
        unit: '#'
      - key: present_number_of_terraced_houses_1965_1984
        unit: '#'
      - key: present_number_of_terraced_houses_1985_2004
        unit: '#'
      - key: present_number_of_terraced_houses_2005_present
        unit: '#'
