---
# Contains mappings of keys used in energy balance CSVs to those used in GQL.
column_groups:
  Network gas:
    - Biogases
    - Natural gas
  Coal incl lignite and peat:
    - Anthracite
    - Coking coal
    - Other bituminous coal
    - Sub-bituminous coal
    - Patent fuel
    - Coke oven coke
    - Gas coke
    - Coal tar
    - Brown coal briquettes
    - Peat and peat products
    - Lignite
  Coal:
    - Anthracite
    - Coking coal
    - Other bituminous coal
    - Sub-bituminous coal
    - Patent fuel
    - Coke oven coke
    - Gas coke
    - Coal tar
    - Brown coal briquettes
  Lignite and peat:
    - Peat and peat products
    - Lignite
  Coal gas:
    - Coke oven gas
    - Blast furnace gas
    - Other recovered gases
  Oil:
    - Oil shale and oil sands
    - Crude oil
    - Natural gas liquids
    - Refinery feedstocks
    - Additives and oxygenates (excluding biofuel portion)
    - Other hydrocarbons
    - Refinery gas
    - Ethane
    - Liquefied petroleum gases
    - Motor gasoline (excluding biofuel portion)
    - Aviation gasoline
    - Gasoline-type jet fuel
    - Kerosene-type jet fuel (excluding biofuel portion)
    - Other kerosene
    - Gas oil and diesel oil (excluding biofuel portion)
    - Fuel oil
    - Naphtha
    - White spirit and special boiling point industrial spirits
    - Lubricants
    - Bitumen
    - Paraffin waxes
    - Petroleum coke
    - Other oil products
    - Pure biodiesels
    - Blended biodiesels
    - Pure bio jet kerosene
    - Blended bio jet kerosene
    - Pure biogasoline
    - Blended biogasoline
    - Other liquid biofuels
  Fossil oil:
    - Oil shale and oil sands
    - Crude oil
    - Natural gas liquids
    - Refinery feedstocks
    - Additives and oxygenates (excluding biofuel portion)
    - Other hydrocarbons
    - Refinery gas
    - Ethane
    - Liquefied petroleum gases
    - Motor gasoline (excluding biofuel portion)
    - Aviation gasoline
    - Gasoline-type jet fuel
    - Kerosene-type jet fuel (excluding biofuel portion)
    - Other kerosene
    - Gas oil and diesel oil (excluding biofuel portion)
    - Fuel oil
    - Naphtha
    - White spirit and special boiling point industrial spirits
    - Lubricants
    - Bitumen
    - Paraffin waxes
    - Petroleum coke
    - Other oil products
  Renewable oil:
    - Pure biodiesels
    - Blended biodiesels
    - Pure bio jet kerosene
    - Blended bio jet kerosene
    - Pure biogasoline
    - Blended biogasoline
    - Other liquid biofuels
  Gasoline:
    - Motor gasoline (excluding biofuel portion)
    - Aviation gasoline
    - Gasoline-type jet fuel
  Kerosene:
    - Kerosene-type jet fuel (excluding biofuel portion)
    - Other kerosene
  Bio-diesel:
    - Pure biodiesels
    - Blended biodiesels
  Bio-kerosene:
    - Pure bio jet kerosene
    - Blended bio jet kerosene
  Biogasoline:
    - Pure biogasoline
    - Blended biogasoline
  Other oil:
    - Oil shale and oil sands
    - Crude oil
    - Other hydrocarbons
    - Additives and oxygenates (excluding biofuel portion)
    - Refinery feedstocks
    - Natural gas liquids
    - Refinery gas
    - Ethane
    - Motor gasoline (excluding biofuel portion)
    - Aviation gasoline
    - Gasoline-type jet fuel
    - Fuel oil
    - Naphtha
    - White spirit and special boiling point industrial spirits
    - Lubricants
    - Bitumen
    - Paraffin waxes
    - Petroleum coke
    - Other oil products
  Waste:
    - Renewable municipal waste
    - Industrial waste (non-renewable)
    - Non-renewable municipal waste
  Fuelmix:
    - Biogases
    - Natural gas
    - Oil shale and oil sands
    - Crude oil
    - Natural gas liquids
    - Refinery feedstocks
    - Additives and oxygenates (excluding biofuel portion)
    - Other hydrocarbons
    - Refinery gas
    - Ethane
    - Liquefied petroleum gases
    - Motor gasoline (excluding biofuel portion)
    - Aviation gasoline
    - Gasoline-type jet fuel
    - Kerosene-type jet fuel (excluding biofuel portion)
    - Other kerosene
    - Gas oil and diesel oil (excluding biofuel portion)
    - Fuel oil
    - Naphtha
    - White spirit and special boiling point industrial spirits
    - Lubricants
    - Bitumen
    - Paraffin waxes
    - Petroleum coke
    - Other oil products
    - Pure biodiesels
    - Blended biodiesels
    - Pure bio jet kerosene
    - Blended bio jet kerosene
    - Pure biogasoline
    - Blended biogasoline
    - Other liquid biofuels
