development:
  adapter: mysql2
  database: etlocal_development
  host: 127.0.0.1
  username: root
  password:
  encoding: utf8
  timeout: 5000

test:
  adapter: mysql2
  database: etlocal_test
  host: 127.0.0.1
  username: root
  password:
  encoding: utf8
  timeout: 5000
  pool: 5
