key: agriculture_advanced
groups:
  - header: electricity_distribution
    type: slider
    items:
      - key: agriculture_final_demand_electricity_agriculture_useful_demand_electricity_parent_share
        flexible: true
        unit: '%'
      - key: agriculture_final_demand_electricity_agriculture_geothermal_parent_share
        unit: '%'
      - key: agriculture_final_demand_electricity_agriculture_heatpump_water_water_ts_electricity_parent_share
        unit: '%'
