key: agriculture_energy_supply
groups:
  - header: gas_chp
    items:
      - key: agriculture_chp_engine_network_gas_demand
        unit: TJ

  - header: biomass_chp
    items:
      - key: agriculture_chp_supercritical_wood_pellets_demand
        unit: TJ

  - header: biogas_chp
    items:
      - key: agriculture_chp_engine_biogas_demand
        unit: TJ
